Add test reporter action

diff --git a/.github/workflows/gh-pages.yml b/.github/workflows/gh-pages.yml
--- a/.github/workflows/gh-pages.yml
+++ b/.github/workflows/gh-pages.yml
@@ -59,7 +59,15 @@ jobs:
                   dotnet-version: 7.x
                   
             - name: Test
-              run: dotnet test AlasdairCooper.Portfolio.Tests/AlasdairCooper.Portfolio.Tests.csproj
+              run: dotnet test AlasdairCooper.Portfolio.Tests/AlasdairCooper.Portfolio.Tests.csproj --logger "trx;LogFileName=test-results.trx"
+
+            - name: Test Report
+              uses: dorny/test-reporter@v1
+              if: success() || failure()    # run this step even if previous step failed
+              with:
+                name: JEST Tests            # Name of the check run which will be created
+                path: /*/test-results.trx   # Path to test results
+                reporter: dotnet-trx        # Format of test results
     deploy:
         needs: test
         name: deploy 🚀
